# @format

runtime: nodejs20
instance_class: F1

env_variables:
  NODE_ENV: "production"
  DB_USER: "admin"
  DB_PASSWORD: "admin1234"
  DB_NAME: "devpath"
  INSTANCE_CONNECTION_NAME: "orbital-signal-457502-f2:asia-southeast2:devpath"
