# @format

runtime: nodejs20
instance_class: F1

env_variables:
  NODE_ENV: "production"
  DB_USER: "admin"
  DB_PASSWORD: "admin1234"
  DB_NAME: "devpath_db"
  INSTANCE_CONNECTION_NAME: "orbital-signal-457502-f2:asia-southeast2:devpath"
  API_KEY: "dev_secret_2609"

beta_settings:
  cloud_sql_instances: "orbital-signal-457502-f2:asia-southeast2:devpath"



